version: '3.8'
services:

  webserver:
    image: tomee
    ports:
      - "7070:8080"
    environment:
      - DB_HOST=mydb
      - DB_USER=sunny
      - DB_PASSWORD=sunny
    depends_on:
      - mydb

